// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdKfzwuZQz4ueQq4bOQzKfdhqjOIZlEnY',
    appId: '1:543729351254:web:77c876b6dff406a44f59f7',
    messagingSenderId: '543729351254',
    projectId: 'auth-last-try',
    authDomain: 'auth-last-try.firebaseapp.com',
    storageBucket: 'auth-last-try.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmf8n7xQzYKNgRe_CF5ryJEOAb4ZanH_M',
    appId: '1:543729351254:android:3014526d4ff5516f4f59f7',
    messagingSenderId: '543729351254',
    projectId: 'auth-last-try',
    storageBucket: 'auth-last-try.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi9IMgHlEQusxXroQYVgfbtwexWIpHLuM',
    appId: '1:543729351254:ios:9d818f68dd4761564f59f7',
    messagingSenderId: '543729351254',
    projectId: 'auth-last-try',
    storageBucket: 'auth-last-try.appspot.com',
    iosClientId: '543729351254-7mauoinrukfj6ei3gh7df74m0pc71tml.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi9IMgHlEQusxXroQYVgfbtwexWIpHLuM',
    appId: '1:543729351254:ios:9d818f68dd4761564f59f7',
    messagingSenderId: '543729351254',
    projectId: 'auth-last-try',
    storageBucket: 'auth-last-try.appspot.com',
    iosClientId: '543729351254-7mauoinrukfj6ei3gh7df74m0pc71tml.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastTry',
  );
}
